id: P54C1C141
initial_creation_type: ocr
source_metadata:
  volumes:
    34e24d2df2d74218b99c6f709bede0fb:
      base_file: v037.txt
      image_group_id: I1PD95882
      title: དཔལ་ཕྱག་ན་རྡོ་རྗེ་ལ་བསྟོད་པ།
      total_pages: 1379
      volume_number: 37
